# Generated by Django 4.2.2 on 2025-07-12 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_reaction_photos_commentaire'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentaire',
            name='reponse',
            field=models.TextField(null=True),
        ),
    ]
